### ISSUE TITLE
Update from 1.2.1 to 1.2.2

### ISSUE THREAD

**Issue by hxmelab** [holomekc/bosch-smart-home-bridge#12]
Hi holomekc, thank you for keeping this project updated!

Unfortunately, I get an error after updating from 1.2.1 to 1.2.2. When the node starts and tries to initiate the lib, the following error occurs: 

24 Apr 22:16:53 - [error] [shc-config:2d20f22b4fb126da] TypeError: BoschSmartHomeBridgeBuilder.builder is not a constructor

With version 1.21 the following constructor is working fine:

const {BoschSmartHomeBridgeBuilder, BshbUtils} = require('bosch-smart-home-bridge');

                this.shc = new BoschSmartHomeBridgeBuilder.builder()
                    .withHost(this.shcip)
                    .withClientCert(this.cert)
                    .withClientPrivateKey(this.key)
                    .withLogger(new ShcLogger())
                    .withIgnoreCertificateCheck(false)
                    .build();

Did the constructor changed by updating the ECMA Script in 1.2.2?

**Comment by holomekc** [comment]
Hi,
Hmm no. The constructor did not change. I updated to ECMA 2022 mostly because of the error causes feature. I will check today (when i do not forget it). I guess I could for some time add an ECMA 2021 version in parallel.

**Comment by holomekc** [comment]
Hi,

where do you see the error? In Travis? I saw that you are using node 10 there. Before 1.2.2 I was still using es5, which is pretty old. So I thought it is time to update.

Nevertheless, I published `bosch-smart-home-bridge@1.2.2-es2017` . Can you please try this version. If this is working I can try to publish ES2022 and ES2017 for some time.

Br,
Chris

**Comment by hxmelab** [comment]
Hi Chris, I added three branches, different behavior occurs in each branch when starting node-red:

With v1.2.1 everything starts as expected:
[https://github.com/hxmelab/node-red-contrib-bosch-shc/tree/update-dependencies-v1_2_1](https://github.com/hxmelab/node-red-contrib-bosch-shc/tree/update-dependencies-v1_2_1)

25 Apr 21:49:53 - [info] Starting flows
25 Apr 21:49:53 - [info] Started flows
25 Apr 21:49:53 - [info] [shc-config:2d20f22b4fb126da] Long polling SHC: 192.168.0.10 with poll Id: f67b7gd1l-296

---------------------------------------------------------------------

With v1.2.2 the already described error occurs:
[https://github.com/hxmelab/node-red-contrib-bosch-shc/tree/update-dependencies](https://github.com/hxmelab/node-red-contrib-bosch-shc/tree/update-dependencies)

25 Apr 21:51:07 - [info] Starting flows
25 Apr 21:51:07 - [error] [shc-config:2d20f22b4fb126da] TypeError: BoschSmartHomeBridgeBuilder.builder is not a constructor
25 Apr 21:51:07 - [info] Started flows

---------------------------------------------------------------------

With v1.2.2-es2017 follwing happens:
[https://github.com/hxmelab/node-red-contrib-bosch-shc/tree/update-dependencies-es2017](https://github.com/hxmelab/node-red-contrib-bosch-shc/tree/update-dependencies-es2017)

25 Apr 21:44:48 - [info] Waiting for missing types to be registered:
25 Apr 21:44:48 - [info]  - shc-config

The only difference of the three branches is the version of the lib. 

Using the following components:
npm 9.6.5
node 18.16.0
node-red 3.0.2

**Comment by holomekc** [comment]
Hmm I will check later again. Can you test removing "new" from the Builder part? This kind of worked for me. I receive a 400 during pairing not yet sure why. I would test this later though.

**Comment by hxmelab** [comment]
Removing "new" was the solution. 

Great, thank you so much!
