### ISSUE TITLE
Can't connect to BSHC-2. Is it compatible?

### ISSUE THREAD

**Issue by X3nnon** [holomekc/bosch-smart-home-bridge#163]
Hello;

I tried to connect to my BSHC-2 with jalibu`s MagicMirror Module (https://github.com/jalibu/MMM-BoschSmartHome) what is based on your api. But got the message: "Can't connect to BSHC". Is your api compatible with BSHC-2 or is it only working with BSHC?

Thanks in advance!

**Comment by holomekc** [comment]
Hi,
It is working fine with the iobroker.bshb which is also based on the lib and I wrote as well. A common mistake with controller 2 is that you need to click the pairing button. Do not hold it for 3s

I hope this helps

**Comment by X3nnon** [comment]
Thank you for your help and your fantastic work, this was the problem.

**Comment by holomekc** [comment]
Great. I am happy that it works now. Have fun.
