### ISSUE TITLE
Tür-/Fensterkontakt II (Plus) not supported

### ISSUE THREAD

**Issue by IstvanTempfli** [holomekc/bosch-smart-home-bridge#169]
Tür-/Fensterkontakt II (Plus) is displaying only an "UNDEFINED" status.
![image](https://github.com/user-attachments/assets/c9ff3d67-e010-4d23-8004-90d38cb7f535)

**Comment by holomekc** [comment]
Hi,
Mine is working fine. Try to stop the adapter, remove the object tree of the device in the object list, and restart the adapter.

**Comment by holomekc** [comment]
No further feedback received
